
-- CHECK

-- UNIQUE

INSERT INTO CLINICA..ESPECIALIDAD(IDESPECIALIDAD,NOMBRE,CAPACIDAD) VALUES
(10,'PEDIATRIA', -30);


SELECT * FROM CLINICA..ESPECIALIDAD;
GO

DELETE FROM CLINICA..ESPECIALIDAD
WHERE IDESPECIALIDAD = 10;


ALTER TABLE CLINICA..ESPECIALIDAD
ADD CONSTRAINT CK_ESPECIALIDAD_CAPACIDAD
CHECK (CAPACIDAD > 0);
GO


INSERT INTO CLINICA..ESPECIALIDAD(IDESPECIALIDAD,NOMBRE,CAPACIDAD) VALUES
(10,'PEDIATRIA', -30);


