-- FOREIGN KEY

INSERT INTO CLINICA..ESPECIALIDAD(IDESPECIALIDAD,NOMBRE,CAPACIDAD) VALUES
(1,'PEDIATRIA', 30),
(2,'PSICOLOGIA',20),
(3,'GINECOLIGIA',25);

SELECT * FROM CLINICA..ESPECIALIDAD;
GO


SET IDENTITY_INSERT CLINICA..MEDICO ON
GO

INSERT INTO CLINICA..MEDICO(IDMEDICO,IDESPECIALIDAD,NOMBRE,APELLIDO,DNI,TELEFONO,CORREO)
VALUES (1,1,'JUAN','VERA','89547698','12345678','JVERA@GMAIL.COM');


INSERT INTO CLINICA..MEDICO(IDMEDICO,IDESPECIALIDAD,NOMBRE,APELLIDO,DNI,TELEFONO,CORREO)
VALUES (1,10,'JUAN','VERA','89547698','12345678','JVERA@GMAIL.COM');